// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAp0XQkppCI3g-xYXH8mClzjj9qbv2dbJk',
    appId: '1:978869807700:web:05cc74742c4aa6f8bddbc1',
    messagingSenderId: '978869807700',
    projectId: 'goodfood-f9521',
    authDomain: 'goodfood-f9521.firebaseapp.com',
    storageBucket: 'goodfood-f9521.appspot.com',
    measurementId: 'G-0HR5MT700Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBy9GwStmWIR0-bBGhaG1Ek5ERDwGCdYcM',
    appId: '1:978869807700:android:5856d6c44efdd3e2bddbc1',
    messagingSenderId: '978869807700',
    projectId: 'goodfood-f9521',
    storageBucket: 'goodfood-f9521.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATDstTDe8VT3Hl1QF7IHR0-68sxk-_Nl0',
    appId: '1:978869807700:ios:743ed661f2edff1dbddbc1',
    messagingSenderId: '978869807700',
    projectId: 'goodfood-f9521',
    storageBucket: 'goodfood-f9521.appspot.com',
    iosClientId: '978869807700-kpoe2ah6np70fhfk416580fp1muvqi4f.apps.googleusercontent.com',
    iosBundleId: 'com.example.goodfoodMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATDstTDe8VT3Hl1QF7IHR0-68sxk-_Nl0',
    appId: '1:978869807700:ios:743ed661f2edff1dbddbc1',
    messagingSenderId: '978869807700',
    projectId: 'goodfood-f9521',
    storageBucket: 'goodfood-f9521.appspot.com',
    iosClientId: '978869807700-kpoe2ah6np70fhfk416580fp1muvqi4f.apps.googleusercontent.com',
    iosBundleId: 'com.example.goodfoodMobile',
  );
}
